### ISSUE TITLE
input要素の横幅が100%になってしまう。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#11]
これは Contact Form 7 や、Bootstrap の仕様によるものかもしれませんが、ページに配置したinput要素の横幅が100%になってしまい、お名前や郵便番号など入力文字数の少ないアイテムの見栄えがちょっとアレな感じです。もしかして、なんらかのclass属性を付与すれば、解決できるのでしょうか…？

**Comment by kurudrive** [comment]
う〜ん、Bootstrapの仕様で たぶん100%にしないのであれば Gridで幅を制御する想定のフレームワークなのではないかなと思います。

**Comment by kurudrive** [comment]
.form-control が横幅100%になってしまうので、 .input_widthAuto クラスを追加すれば auto になるように変更しました。
