### ISSUE TITLE
div.siteContent, div.site-main の padding-bottom がちょっと大きい？

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#13]
まだ調整段階にあるかと思いますけれども、見出しに挙げた２つのdiv要素に設定された padding-bottom  の合計値が 7em あって、フッター上部のウィジェットとの間隔が大きく見えます。たとえば、ウィジェットに薄い背景色が設定されていれば違和感がなく閲覧できると思いますが、同一の背景色に、同一の書式で表示されるために、間隔の大きさが際立って感じられるようです。これもご参考までに…。

**Comment by kurudrive** [comment]
あ〜、これはちょっと最近のデザインの流れとか、今回文字を大きめにしていたりとか、モバイル時に領域の違いがわかりやすいようにとか、今後スケボーブログみたいに何か装飾を個別で出来るようにという事を踏まえてなので、ここに関しては好みにあわせて近日実装のCSSて入力出来る画面から調整いただくという形でご容赦願います。
