### ISSUE TITLE
div.entry-body に配置される h4 の color が、固定されている。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#14]
これもすでにご認識のことかもしれませんが、div.entry-body に設置した h4（見出し４）の文字色が、#337ab7 に固定されてしまっています。よろしくお願いします。

**Comment by kurudrive** [comment]
修正しました。急ぎで変更する場合は 下記ページから落としてください。
https://github.com/kurudrive/Lightning/tree/develop

ただ、他のも数件修正した上で 6/23 の19時頃にまとめてアップします。
