### ISSUE TITLE
meta (description) に、タグがそのまま出力されてしまう。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#16]
プラグインの仕様かもしれませんが、現在 meta (description) に本文のソースがそのまま提供されているようです。したがって冒頭に h2 などの見出しを持ってくると、概要文の中にタグが入ってしまいます。

**Comment by jjiijjii** [comment]
og:description には、タグが取り除かれたテキストが入っていますね！

**Comment by kurudrive** [comment]
プラグイン側で修正
https://github.com/kurudrive/VK-All-in-one-Expansion-Unit/commit/69723ee15d338aa0da152a5c31a74f950b803d68
