### ISSUE TITLE
Copyright って、テーマを編集しなきゃだめですか？

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#19]
サイトのタイトルと、運営者が異なることもあると思いますので、著作権表示をある程度自由に書き換えられると良いのではないかな、と思いました。個人的には、メインのサイトへのリンクができるように、a要素の使用を許可していただけると嬉しいです。

**Comment by kurudrive** [comment]
footer.phpを直接書き換えるか、有料ですが下記プラグインを使うと変更する事ができます。
http://lightning.bizvektor.com/ja/plugins/lightning_copyright_customizer
