### ISSUE TITLE
div.section.siteContent 内のカラム間隔が大きい。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#23]
おそらく内包しているbootstrapのカラム指定が、col-md-8と、col-md-3になっているせいだと思います。意図して設定されたものであれば、申し訳ありません。

**Comment by kurudrive** [comment]
8-4 だと間隔なさすぎなので、意図的にこうしています。
もし 8-4 にしたい場合は直接テンプレートを編集する必要がありますが、
今まだいろいろ調整が多い段階なので、今カスタマイズする事はおすすめしていません。
今しばらくお待ちください。
