### ISSUE TITLE
トップページ固定ページ使用時に固定用ページが選択されていない場合に Notice: Undefined index

### ISSUE THREAD

**Issue by hinaloe** [kurudrive/Lightning#42]
表題の状況(そもそもそのような状態がおかしいが)の際に以下のNoticeが表示される。

```
Notice: Undefined index: name in .../wp-content/themes/lightning/module_panList.php on line 53
```

**Comment by kurudrive** [comment]
症状が再現出来なかったのですが、

* 使用したのはWordPress.orgのものでしょうか？GitHubの方でしょうか？
* 固定ページを使用に設定、固定ページを未選択で、投稿ページは何か設定していますか？
* 症状が出るのはどのページになりますか？トップページ？投稿トップ？

以上よろしくお願いいたします。

**Comment by hinaloe** [comment]
> 使用したのはWordPress.orgのものでしょうか？GitHubの方でしょうか？

WordPress.orgの方でした

> 固定ページを使用に設定、固定ページを未選択で、投稿ページは何か設定していますか？

カスタマイザー内でいずれも見選択でした。(このまま通常ページに戻ると固定ページを使用が解除されるかも)

> 症状が出るのはどのページになりますか？トップページ？投稿トップ？

トップページです。

**Comment by kurudrive** [comment]
ご連絡ありがとうございます！
GitHubに上がっている最新版で現在更新申請中のバージョンではそもそもトップページではmodule_panList.php が読み込まれないので、ご連絡の症状にはならなくなっていますが、念のためnotice対策を追加しました。
