### ISSUE TITLE
VK_固定ページ本文に指定しないアイキャッチ画像

### ISSUE THREAD

**Issue by na2kimu** [kurudrive/Lightning#56]
素敵なテーマをありがとうございます。

「VK_固定ページ本文」をトップページコンテンツエリア上部に設置しました。
そうすると、ブログ（投稿記事）に設定されたアイキャッチ画像がフロントページのこの部分に表示されてしまいます。

指定した固定ページにはアイキャッチ画像もその他画像も設置していません。
指定した固定ページに「アイキャッチ画像を自動挿入しない」のチェックを入れても、ブログに設定されたアイキャッチ画像が表示されます。

投稿したブログの記事に「アイキャッチ画像を自動挿入しない」のチェックを入れると、「VK_固定ページ本文」エリアに表示された画像は消えます。

フロントページのテンプレートなどは触っていません。

確認していただけたら嬉しいです。

**Comment by nc30** [comment]
https://github.com/kurudrive/VK-All-in-One-Expansion-Unit/commit/5ea31471a53cc8e8356d28fa8f376c07484a46c5

**Comment by kurudrive** [comment]
対応済みにつきcloseとします。
ご報告ありがとうございました。
