### ISSUE TITLE
Lightning Works Unitのカスタム投稿タイプの年、月アーカイブが表示されません

### ISSUE THREAD

**Issue by nanaironanairo** [kurudrive/Lightning#59]
Lightning Works Unitを購入し手順通り設定したつもりなのですが、
年、月別のアーカイブのリンクをクリックすると次のアドレスに飛びます。
又、その際の表示内容はpostのアーカイブのものです。

http://ドメイン/date/2016?post_type=works_b?post_type=works_b

手動で次のように入力すると、年別のアーカイブが表示されます。

http://ドメイン/date/2016?post_type=works_b

実はビズベクトルでも同様の現象が起きた事があり、
対応していただいて解消したのですが、今回も何等かの不具合ではないかとおもい書き込みさせていただきました。
どうぞよろしくお願いします。

**Comment by kurudrive** [comment]
ご連絡大変遅くなり申し訳ありません。
ExUnitのアーカイブウィジェットで、状況によって発生する事が確認できましたのでExUnitの修正版をアップいたしました。
ExUnitをアップデートしてご確認いただけますでしょうか？
以上よろしくお願いいたします。
