### ISSUE TITLE
ヘッダーおよびグローバルナビの固定を解除したい

### ISSUE THREAD

**Issue by applepie3** [kurudrive/Lightning#60]
ページをスクロールダウンした時にロゴが潰れ、
スクロールアップしても潰れたまま元に戻りません。
固定を解除する方法をご教示ください。
よろしくお願いします。

**Comment by applepie3** [comment]
ヘッダーおよびグローバルナビの固定解除は自己解決しました。

しかし、ロゴの伸縮は相変わらず起こり、ページをスクロールダウンすれば潰れ、スクロールアップしても潰れたまま元に戻りません。

ロゴの伸縮をなくす方法を教えてください。よろしくお願いします。

**Comment by kurudrive** [comment]
仕様変更いたしました。
http://lightning.vektor-inc.co.jp/ja/archives/remove-header-fixed
