### ISSUE TITLE
[ Add Function ] Lightning本体にスキン切り替え機能の実装

### ISSUE THREAD

**Issue by kurudrive** [kurudrive/Lightning#61]
* 拡張スキンのプラグインが有効化されている場合はカスタマイザーでスキン変更用の項目を表示してプルダウンでスキンを変更出来るように
* カスタマイザーのプルダウンの上あるいは下に下記の表記

---

スキンを変更したら一度保存してください。
Please save Once you change the skin.

保存した後で再読み込みをすると、スキン固有の設定項目が表示されます。
If you reload after the saving, it will be displayed skin-specific configuration items.

※スキンによっては固有の設置項目がない場合もあります。
*There is also a case where there is no skin-specific installation item.

---

* Lightning 標準のスキン名は 「Lightning Origin」

**Comment by nc30** [comment]
fa45f9536abd57aad03c0c996b6888683c088581
3c77cd49bd83e8a9dbd757e68f67783e4e28198e
4cec860b6efedf788f1d22adf15cde79ac651fe5
