### ISSUE TITLE
WP4.5でのJqueryエラー対応方法を教えて下さい。

### ISSUE THREAD

**Issue by cucuruz** [kurudrive/Lightning#62]
仕様
Wordpress4.5.1 Lightningは最新
仕様プラグイン
VK All in One Expansion Unit
Welcart e-Commerce
（最小構成）でも同エラーが出ます
確認方法
ブラウザの要素を検証
発生内容
JQMIGRATE: Migrate is installed, version 1.4.0 にて下記のエラーが発生しています。
SCRIPT1002: Syntax error
上記により下記の事ができません。
　商品ページの表示
　カート投入ボタン
Welcart側からはテーマ側でエラーを出さないようにしないと使用できないとの
アナウンスが有り困っております。
どのような方法でエラーを出さないようにできますでしょうか？
動作確認ページのURLを貼付したいのですがこちらにLink貼っても
問題ありますか？

**Comment by kurudrive** [comment]
LightningとExUnitの最新版をアップしましたのでとりあえずアップデートしてみてください。
もしそれで治らないようでしたらこちらに該当ページのリンクを貼ってください。

**Comment by cucuruz** [comment]
GWの中、早々のご対応ありがとうございます。
早速、両方共、バージョンを上げてみましたがエラーは出ております。
該当ページも正常に表示できておりません。

下記のページです
https://www.wakaiss.com/bmp-002-bk/

よろしくお願いいたします。

**Comment by kurudrive** [comment]
https://www.wakaiss.com/bmp-002-bk/
について確認しましたが、

> SCRIPT1002: Syntax error
に関しては症状が出ていないのでブラウザ依存かもしれません。
ブラウザは何を使用していますでしょうか？

> JQMIGRATE: Migrate is installed, version 1.4.0 
はだたのログでエラーではなく、Lightning & ExUnitを外して別のテーマにしても出ますので、
Lightning & ExUnit 固有の症状でもないと思います。

http://hacknote.jp/archives/18598/

> 上記により下記の事ができません。
>　商品ページの表示
>　カート投入ボタン

何となく設定方法が何か抜けているのではないかなと言う気はしますが、
今一度ご確認ください。

**Comment by cucuruz** [comment]
レスありがとうございます。
非常に美しいテーマなので使用したいです。
現在設定を確認しておりますが1点確認させて下さい。
Lightning & ExUnit +WelcartをローカルXampp環境で試した所、動きました。
そこで、環境の違いを検証しております。
実際のサーバー（SuiteX）はPHPのバージョン5.3.3です。
ローカル環境は5.4.7ですがバージョンに関連するエラーだと思われますか？

**Comment by kurudrive** [comment]
あー、
WordPressが必須は5.2.4〜ですが推奨は PHP 5.6〜
ですし、
WelCartは動作要件 PHP 5.4〜
http://www.welcart.com/wc-condition/
ですね。たぶんそれが原因ではないかと思いまする。
