### ISSUE TITLE
Webmaster Tools において、リンク切れの報告が上がる。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#7]
もしかすると Lightning に起因する問題ではないかもしれませんが、このテーマならびにプラグインを使用したサイトにおいて、必ず「mobile/」と「m/」というディレクトリにリンク切れの報告が上がってきます。ご参考あめに。

**Comment by kurudrive** [comment]
ウチのサイトだと出ないのでこれはテーマの問題ではないかなと思います。
