### ISSUE TITLE
グローバルメニューのサブアイテムを多数並べようとすると、画面の縦幅から溢れたアイテムを選択できない。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#8]

**Comment by jjiijjii** [comment]
http://wr-oris.com/
このサイトの「修理対応機種一覧」にマウスオーバーをしたとき、画面の縦幅いっぱいにサブアイテムが表示されるのですが、スクロールをしてもメニューそのものの位置が固定されているので、下の方のアイテムを選択できません。減らせばよい、というだけの話ですけど。

**Comment by kurudrive** [comment]
う...ちょっと考えます（＝ｗ＝；

**Comment by kurudrive** [comment]
現行版で修正済みのためcloase
