### ISSUE TITLE
スマートフォンで表示させたとき、メニューをスクロールできるようことが認識しづらい…。

### ISSUE THREAD

**Issue by jjiijjii** [kurudrive/Lightning#9]
画面の幅を目一杯狭めたとき、スマートフォンで表示させたとき、右上に表示されるハンバーガーメニュー（？）をクリックできることは明らかなのですが、いざ展開されたメニューをスクロールできることがちょっと分かりづらいようです。丸ごと展開して、コンテンツを相対的にスライドさせても良いのではないでしょうか？ご参考までに。

**Comment by kurudrive** [comment]
ですよねー。
これ Bootstapので用意されてるナビゲーションで、出来るだけ自前のCSS書かずにBootstrap標準でいきたいとは思って使ったのですが、僕もあれ？っと思いました。
今のタイミングではちょっと難しいですが、後々作り変えます。

**Comment by kurudrive** [comment]
Ligthning Advanced unit で横からスライドするメニューを実装済みのため close
